### ISSUE TITLE
Set up Mailman service at lists.bisq.network

### ISSUE THREAD

**Issue by cbeams** [bisq-network/lists#1]
Per discussions in Slack.

@emzy, please let me know what you need for DNS records. Ideally via an issue in bisq-network/dns, but as a comment here is also fine.

**Comment by Emzy** [comment]
I'm in the progress of setting it up.
Waiting for the DNS settings.

**Comment by cbeams** [comment]
bisq-network/dns#3 is complete, thanks @Emzy.

**Comment by cbeams** [comment]
Closing as complete. Mailman and Pipermail are now up and running at https://lists.bisq.network. Thanks @emzy!
