### ISSUE TITLE
Create bisq-contrib@lists.bisq.network

### ISSUE THREAD

**Issue by cbeams** [bisq-network/lists#2]
This is the first, and probably only list that we'll host for a while. As the name suggests, this list is specifically for Bisq _contributors_ as the term is defined in the [Roles](https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#appendix-a-roles) section of Phase Zero paper.

**Comment by cbeams** [comment]
Closing as complete. The bisq-contrib list is now up and available at https://lists.bisq.network/listinfo/bisq-contrib.

**Comment by ManfredKarrer** [comment]
Cool!

**Comment by cbeams** [comment]
> Cool!

Agreed :) I'll send a couple messages to the list soon to get the ball rolling.
